Project2/Project2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from app1 import views
from app2 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('app2/',include('app2.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Project2/app1/urls.py
# from django.contrib import admin
from django.urls import path
from app1 import views
app_name="app1"
urlpatterns = [
    # path('admin/', admin.site.urls),
      path('',views.home,name='home'),
      path('addbook',views.addbook,name='addbook'),
      path('addbook1', views.addbook1, name='addbook1'),
      path('view/<int:p>/', views.view_book, name='view'),
      path('edit/<int:p>/',views.edit_book,name='edit'),
      path('delete/<int:p>/', views.delete_book, name='delete'),
      path('viewbook',views.viewbook,name='viewbook'),
      path('viewpersons',views.viewpersons,name='viewpersons'),
      path('addpersons',views.addpersons,name='addpersons'),
      path('addpersons1',views.addpersons1,name='addpersons1'),
      path('fact',views.fact,name='fact'),
      path('register',views.register,name='register'),
      path('user_login',views.user_login,name='user_login'),
      path('user_logout',views.user_logout,name='user_logout'),
      path('adminsignup', views.admin_signup, name='adminsignup'),
      path('teachersignup', views.teacher_signup, name='teachersignup'),
      path('personsignup', views.person_signup, name='personsignup'),
]

Project2/app2/urls.py
# from django.contrib import admin
from django.urls import path
from app2 import views
app_name="app2"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='login'),
    path('user_logout', views.user_logout, name='logout'),
]

Project2/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Book(models.Model):
    title=models.CharField(max_length=30)
    author=models.CharField(max_length=30)
    price=models.IntegerField()
    pdf=models.FileField(upload_to='book/pdf')
    cover=models.ImageField(upload_to='book/img',null=True,blank=True)
    def __str__(self):
      return self.title


class Person(models.Model):
    name=models.CharField(max_length=30)
    place=models.CharField(max_length=30)
    age=models.IntegerField()
    def __str__(self):
        return self.name


class Myuser(AbstractUser):
    place=models.CharField(max_length=30)
    phone=models.IntegerField()
    is_admin=models.BooleanField(default=False)
    is_teacher=models.BooleanField(default=False)
    is_person=models.BooleanField(default=False)

# class Customuser(AbstractUser):

Project2/app2/models.py
from django.db import models

# Create your models here.

Project2/app1/forms.py
from app1.models import Book
from django import forms
class bookform(forms.ModelForm):
    class Meta:
        model=Book
        fields='__all__'


from app1.models import Person
from django import forms
class personform(forms.ModelForm):
    class Meta:
        model=Person
        fields='__all__'

Project2/app1/views.py
from django.shortcuts import render
from app1.models import Book
from app1.models import Person
from app1.models import Myuser
from app1.forms import bookform
from app1.forms import personform
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages


def home(request):
    return render(request,'home.html')

def fact(request):
    if(request.method=="POST"):
        n=int(request.POST['n'])
        f=1
        for i in range(1,n):
            f=f*i
            return render(request,'fact.html',{'f':f})
    return render(request,'fact.html')

def addbook(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        f=request.FILES['f']
        i=request.FILES['i']
        b=Book.objects.create(title=t,author=a,price=p,pdf=f,cover=i)
        b.save()
        return viewbook(request)
    return render(request,'addbook.html')

def addbook1(request):
    f=bookform()
    if(request.method=="POST"):
        f=bookform(request.POST)
        if f.is_valid():
            f.save()
            return viewbook(request)
    return render(request,'addbook1.html',{'f':f})

def addpersons(request):
    if(request.method=="POST"):
        n=request.POST['n']
        p=request.POST['p']
        a=request.POST['a']
        b=Person.objects.create(name=n,place=p,age=a)
        b.save()
        return viewpersons(request)
    return render(request,'addpersons.html')

def addpersons1(request):
    f=personform()
    if(request.method=="POST"):
        f=personform(request.POST)
        if f.is_valid():
         f.save()
         return viewpersons(request)
    return render(request,'addpersons1.html',{'f':f})

def viewbook(request):
    k=Book.objects.all()
    return render(request,'viewbook.html',{'b':k})


def viewpersons(request):
     k=Person.objects.all()
     return render(request,'viewpersons.html',{'b':k})

def view_book(request,p):
    b=Book.objects.get(id=p)
    return render(request,'viewbook.html',{'b':b})

def delete_book(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return viewbook(request)

def edit_book(request,p):
    b=Book.objects.get(id=p)
    f=bookform(instance=b)
    if(request.method=="POST"):
        f=bookform(request.POST,request.FILES,instance=b)
        if f.is_valid():
            f.save()
            return viewbook(request)
    return render(request,'addbook1.html',{'f':f})


def register(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        s=request.POST['s']
        n=request.POST['n']
        u=Myuser.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p,place=s,phone=n)
        u.save()
    return render(request,'register.html')

def admin_signup(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        s=request.POST['s']
        n=request.POST['n']
        u=Myuser.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p,place=s,phone=n)
        u.is_admin=True
        u.save()
        return home(request)
    return render(request,'adminsignup.html')


def teacher_signup(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        s=request.POST['s']
        n=request.POST['n']
        u=Myuser.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p,place=s,phone=n)
        u.is_teacher=True
        u.save()
        return home(request)
    return render(request,'teachersignup.html')


def person_signup(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        s=request.POST['s']
        n=request.POST['n']
        u=Myuser.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p,place=s,phone=n)
        u.is_person=True
        u.save()
        return home(request)
    return render(request,'personsignup.html')


def user_login(request):
     if(request.method=="POST"):
       u = request.POST['u']
       p = request.POST['p']
       user=authenticate(username=u,password=p)
       if (user and user.is_admin==True):
           login(request,user)
           return render(request,'adminhome.html')
       elif (user and user.is_teacher==True):
           login(request,user)
           return render(request,'teacherhome.html')
       elif (user and user.is_person==True):
           login(request,user)
           return render(request,'personhome.html')
       else:
        messages.error(request,"INVALID CREDENTIALS")
     return render(request,'user_login.html')

def user_logout(request):
        logout(request)
        return user_login(request)

Project2/app2/views.py
from django.shortcuts import render

def register(request):
    return render(request,'register.html')

def user_login(request):
    return render(request,'user_login.html')

def user_logout(request):
    return render(request,'user_logout.html')

Project2/templates/addbook.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>ADD BOOK</h1>

<form method="POST" enctype="multipart/form-data">
   {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label text-primary">Title</label>
    <input type="text" class="form-control " name="t">
  </div>
  <div class="mb-3">
    <label  class="form-label text-primary">Author</label>
    <input type="text" class="form-control " name="a">
  </div>
  <div class="mb-3">
    <label  class="form-label text-primary">Price</label>
    <input type="text" class="form-control " name="p">
  </div>
    <div class="mb-3">
    <label  class="form-label text-primary">Pdf</label>
    <input type="file" class="form-control " name="f">
  </div>
    <div class="mb-3">
     <label  class="form-label text-primary">Cover</label>
    <input type="file" class="form-control " name="i">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

Project2/templates/addbook1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>ADD BOOK</h2>

<form method="POST">
    {% csrf_token %}
    <table>
{{f.as_table}}
    </table>
    <div class="mb-3">

        <input type="submit" class="btn btn-primary">
    </div>
</form>
{% endblock %}

Project2/templates/addpersons.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>ADD PERSONS</h1>

<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label text-primary">Name</label>
    <input type="text" class="form-control " name="n">
  </div>
  <div class="mb-3">
    <label  class="form-label text-primary">Place</label>
    <input type="text" class="form-control " name="p">
  </div>
  <div class="mb-3">
    <label  class="form-label text-primary">Age</label>
    <input type="text" class="form-control " name="a">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

Project2/templates/adminhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>ADMIN HOME PAGE</h1>

</body>
</html>

Project2/templates/adminsignup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>ADMIN REGISTER PAGE</h1>

<form method="POST" class="border border-3 border-danger">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label text-light">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>
  <div class="mb-3">
  <label class="form-label text-light">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">E-mail</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your email">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password to be given">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Place</label>
  <input type="text" class="form-control" name="s" placeholder="Enter your place">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Phone number</label>
  <input type="number" class="form-control" name="n" placeholder="Enter your phone number">
</div>
     <div class="mb-3">
    <input type="submit" value="Register">
    </div>
</form>
{% endblock %}

Project2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
                          {% if Myuser.is_authenticated %}
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:addbook'%}">Addbook Page</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:viewbook'%}">Viewbook</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:addbook1'%}">Addbook 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:addpersons'%}">Addpersons</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:addpersons1'%}">Addpersons1</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:viewpersons'%}">Viewpersons</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:fact'%}">Factorial Page</a>
        </li>
                {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Registeration
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app1:adminsignup' %}">ADMIN SIGNUP</a></li>
            <li><a class="dropdown-item" href="{% url 'app1:teachersignup' %}">TEACHER SIGNUP</a></li>
            <li><a class="dropdown-item" href="{% url 'app1:personsignup' %}">PERSON SIGNUP</a></li>
          </ul>
        </li>
                  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:user_login'%}">Login</a>
        </li>
                  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:user_logout'%}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

Project2/templates/fact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 class="text-center">FACTORIAL PAGE</h1>
<form method="POST">
     {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label text-primary">Number</label>
    <input type="number" class="form-control"  name="n" placeholder="Enter the number">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button><br><br><br><br>
</form>
{% if fact %}
<h1>Factorial is :{{f}} </h1>
{% endif %}
{% endblock %}

Project2/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>HOME PAGE</h1>

{% endblock %}

Project2/templates/personhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>PERSON HOME PAGE</h1>
</body>
</html>

Project2/templates/personsignup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>PERSON REGISTER PAGE</h1>

<form method="POST" class="border border-3 border-danger">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label text-light">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>
  <div class="mb-3">
  <label class="form-label text-light">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">E-mail</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your email">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password to be given">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Place</label>
  <input type="text" class="form-control" name="s" placeholder="Enter your place">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Phone number</label>
  <input type="number" class="form-control" name="n" placeholder="Enter your phone number">
</div>
     <div class="mb-3">
    <input type="submit" value="Register">
    </div>
</form>
{% endblock %}

Project2/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>REGISTER PAGE</h1>

<form method="POST" class="border border-3 border-danger">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label text-light">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>
  <div class="mb-3">
  <label class="form-label text-light">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">E-mail</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your email">
</div>
  <div class="mb-3">
    <label  class="form-label text-light">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password to be given">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Place</label>
  <input type="text" class="form-control" name="s" placeholder="Enter your place">
</div>
      <div class="mb-3">
  <label class="form-label text-light">Phone number</label>
  <input type="number" class="form-control" name="n" placeholder="Enter your phone number">
</div>
     <div class="mb-3">
    <input type="submit" value="Register">
    </div>
</form>
{% endblock %}

Project2/templates/teacherhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>TEACHER HOME PAGE</h1>

</body>
</html>

Project2/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>VIEW  PAGE</h1>
<!--<table class="table table-bordered">-->
<!--    <tr>-->
<!--        <th>TITLE</th>-->
<!--        <th>AUTHOR </th>-->
<!--        <th>PRICE</th>-->
<!--    </tr>-->
<!--    {% for i in b %}-->
<!--    <tr>-->
<!--        <td>{{i.title}}</td>-->
<!--        <td>{{i.author}}</td>-->
<!--        <td>{{i.price}}</td>-->
<!--    </tr>-->
<!--{% endfor %}-->
<!--</table>-->

<div class="text-white">
<ol >Library</ol>
<ul> BOOK DETAILS:</ul>
    <li><a href="{{b.pdf.url}}">DOCUMENT</a></li><br>
    <li>TITLE:{{b.title}}</li><br>
    <li>AUTHOR:{{b.author}}</li><br>
    <li>PRICE:{{b.price}}</li><br>
    <li><img src="{{b.cover.url}}" height="100px" width="100px"></li><br>
</div>
{% endblock %}

Project2/templates/viewpersons.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>VIEW PERSON DETAILS PAGE</h1>

<div class="text-white">
<ol >Library</ol>
{% for i in b %}
<ul>PERSON DETAILS:</ul>
<li>NAME:{{i.name}}</li><br>
<li>PLACE:{{i.place}}</li><br>
<li>AGE:{{i.age}}</li><br>
{% endfor %}
    </div>

{% endblock %}